#!/bin/bash
../bin/strip-docker-image -i nginx -t stripped-nginx  \
	       -x 80 \
	       -p nginx  \
	       -f /etc/passwd \
	       -f /etc/group \
	       -f /bin/ls \
	       -f /bin/cat \
	       -f /bin/sh \
	       -f /bin/mkdir \
	       -f /bin/ps \
	       -f /var/run \
	       -f /var/log/nginx \
	       -f /var/cache/nginx \
	       -f /lib/x86_64-linux-gnu
